name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-11
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'true'
        fetch-depth: 0
    - name: Deps
      id: deps
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        cd /Users/runner/work/futurerestore/futurerestore/.github/workflows
        ./deps.sh
    - name: Build
      id: build
      run: |
        cd /Users/runner/work/futurerestore/futurerestore/.github/workflows
        ./build.sh
    - name: Archive
      id: archive
      uses: actions/upload-artifact@v2
      with:
        name: futurerestore
        path: |
          /Users/runner/work/futurerestore/futurerestore/.github/workflows/futurerestore
